### ISSUE TITLE
Brightness doesn't change

### ISSUE THREAD

**Issue by nc1890e** [prueker/METARMap#1]
No matter what value I set LED_BRIGHTNESS to there seems to be no change. Everything else is working flawlessly! Thanks!

**Comment by gabepari** [comment]
In metar.py you need to change:
`pixels = neopixel.NeoPixel(LED_PIN, LED_COUNT, pixel_order = LED_ORDER, auto_write = False`
to:
`pixels = neopixel.NeoPixel(LED_PIN, LED_COUNT, brightness = LED_BRIGHTNESS, pixel_order = LED_ORDER, auto_write = False`
