### ISSUE TITLE
startup.sh not working

### ISSUE THREAD

**Issue by gabepari** [prueker/METARMap#2]
Can't seem to get the startup.sh routine to work.  If I just run the .py straight from rc.local it works fine.  Also running the .py from crontab works to keep it updating.  Any reason I should debug further and get the .sh working??

**Comment by prueker** [comment]
Make sure that you have given the script proper execute permissions using chmod.
I have mine running fine with 755 as the permission mask.

After that if you want to manually execute it you just type: 
`./startup.sh`
 if you're in the same directory.
