### ISSUE TITLE
Dim for Windy Conditions without Blinking

### ISSUE THREAD

**Issue by jimland58** [prueker/METARMap#20]
Is there an easy way to change the code so there is Wind Animation without the blinking?  What I would like it to do is just keep the lights constantly dim, at the Fade brightness levels, for any airports that are windy.  Maybe the code could select this option when it sees the Blinking Speed = 0.0 and the Activate_Windcondition_Animation = True?

**Comment by prueker** [comment]
You can achieve this, if on line 221, you take out `and windCycle == True` that way it will always keep the FADE color if it's windy at an airport.
So the line just becomes:
`windy = True if (ACTIVATE_WINDCONDITION_ANIMATION and (conditions["windSpeed"] > WIND_BLINK_THRESHOLD or conditions["windGust"] == True)) else False`

It will still blink for lightning (if you have that activated), if you also wanted to remove the blinking for lightning, you'd do the same on the lightningConditions line right below on line 222 and take out `and windCycle == False`.
Note that lightning will then take precedence over wind and would keep the LED white entirely if lightning is reported.

One more side note/tip: when I just tested it, it wasn't very easy for me to differentiate between the FADE LEDs and the normal ones without the blinking, so you might also want to reduce the fade colors in the configuration to be a bit more dim (e.g. reducing them from 125 to 60).
