### ISSUE TITLE
Update to metar.py?

### ISSUE THREAD

**Issue by dandspach** [prueker/METARMap#23]
I've been trying to follow the discussion on adding a yellow led for windgusts and can't quite seem to make it all work.  I'm not sure where to edit the code to include the features mentioned in the comments.

Possible enhancements:
1.  HIGH_WINDS_THRESHOLD - addition of yellow led to display for windspeeds & windgusts at or above the WIND_BLINK_THRESHOLD
2.  Lightning Feature enhancements mentioned in the discussion

Any idea when the metar.py file can/will be updated to include this and other functionality mentioned in the comments and discussion on the original article?

Thanks again.  Just finished with my project and will post pics.

**Comment by prueker** [comment]
Thanks for the reminder.

I just pushed a new update to add both improvements.
