### ISSUE TITLE
Setting the LED Status loops 

### ISSUE THREAD

**Issue by SammyGuichelaar** [prueker/METARMap#27]
I made 2 board, and everything is working perfectly, except for the fact that it keep looping while setting the status of each LED.

It finishes setting the status, then does it again and again. This goes on for about 4 minutes before it finally 'finalises'. Everything else works, the cronjob keeps the leds updated every 2 minutes.

The side effect of the loop seems to be that when the wind is higher than what is defined it does not fade, but either just indicate the METAR code for the airport, or bugs around.

I assume the issue with with the airports file, because if I set only one LED then it works fine.

> Setting LED 0 for KALW to VFR (255, 0, 0)
> Setting LED 1 for KPSC to VFR (255, 0, 0)
> Setting LED 2 for KLWS to VFR (255, 0, 0)
> Setting LED 3 for KPUW to VFR (255, 0, 0)
> Setting LED 4 for KGEG to VFR (255, 0, 0)
> Setting LED 5 for KSFF to VFR (255, 0, 0)
> Setting LED 6 for KDEW to VFR (255, 0, 0)
> Setting LED 7 for KCOE to VFR (255, 0, 0)
> Setting LED 8 for KSZT to VFR (255, 0, 0)
> Setting LED 9 for K65S to VFR (255, 0, 0)
> 
> Setting LED 0 for KALW to VFR (255, 0, 0)
> Setting LED 1 for KPSC to VFR (255, 0, 0)
> Setting LED 2 for KLWS to VFR (255, 0, 0)
> Setting LED 3 for KPUW to VFR (255, 0, 0)
> Setting LED 4 for KGEG to VFR (255, 0, 0)
> Setting LED 5 for KSFF to VFR (255, 0, 0)
> Setting LED 6 for KDEW to VFR (255, 0, 0)
> Setting LED 7 for KCOE to VFR (255, 0, 0)
> Setting LED 8 for KSZT to VFR (255, 0, 0)
> Setting LED 9 for K65S to VFR (255, 0, 0)
> 
> Setting LED 0 for KALW to VFR (255, 0, 0)
> Setting LED 1 for KPSC to VFR (255, 0, 0)
> Setting LED 2 for KLWS to VFR (255, 0, 0)
> Setting LED 3 for KPUW to VFR (255, 0, 0)
> Setting LED 4 for KGEG to VFR (255, 0, 0)
> Setting LED 5 for KSFF to VFR (255, 0, 0)
> Setting LED 6 for KDEW to VFR (255, 0, 0)
> Setting LED 7 for KCOE to VFR (255, 0, 0)
> Setting LED 8 for KSZT to VFR (255, 0, 0)
> Setting LED 9 for K65S to VFR (255, 0, 0)
> 
> (4 MINUTES LATER)
> 
> 
> Done

**Comment by prueker** [comment]
The loop is normal if you're using any of the interactive features and is based on the `BLINK_TOTALTIME_SECONDS` variable.

As for the airports file, make sure you don't have any blank lines, only the lines with airports in it.
