### ISSUE TITLE
AttributeError and NameError in metar.py when updating for Sunrise/Sunset Delta time

### ISSUE THREAD

**Issue by lynolamero** [prueker/METARMap#31]
I posted in comments.  This is probably the better place.  
Need some help with this one:

pi@METAR-MAP:~ $ sudo python3 metar.py
Running metar.py at 31/01/2022 15:00
LocationInfo(name='Seattle', region='USA', timezone='US/Pacific', latitude=47.6, longitude=-122.31666666666666)

Traceback (most recent call last):
File "metar.py", line 83, in 
ast = astral.Astral()
AttributeError: module 'astral' has no attribute 'Astral'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "metar.py", line 105, in 
BRIGHT_TIME_START = (sun['sunrise'] + timedelta(minutes=DIM_OFFSET_TIME)).time()
NameError: name 'timedelta' is not defined

-----astral was loaded already--------
Requirement already satisfied: astral in /usr/local/lib/python3.7/dist-packages (2.2)
Requirement already satisfied: pytz in /usr/local/lib/python3.7/dist-packages (from astral) (2020.4)
--------------
Any help would be appreciated. Thanks!

**Comment by prueker** [comment]
Please keep the comments or issues you have with the open PR's in those respective PR comment chains (In this case #29 ) as they are not part of the main code.
