### ISSUE TITLE
Syntax Errors after updating for Calm Winds

### ISSUE THREAD

**Issue by lynolamero** [prueker/METARMap#32]
I'm getting some syntax errors in this file now.  See <<<< notes below.

if condition["windSpeed"] == 0:
draw.text((x, top + 15), "Calm", font=fontSmall, fill=255)
else:
draw.text((x, top + 15), condition["windDir"] + "@" + str(condition["windSpeed"]) + ("G" + str(condition["windGust$ <<<< This ends abruptly should it be: **str(condition["windGust"])** ????

draw.text((x + 64, top + 15), str(condition["vis"]) + "SM " + condition["obs"], font=fontSmall, fill=255) <<<< I think the 'str' command is missing for "obs".  This line should be: draw.text((x + 64, top + 15), str(condition["vis"]) + "SM " + **str**(condition["obs"]**)**, font=fontSmall, fill=255)

**Comment by prueker** [comment]
Please keep the comments or issues you have with the open PR's in those respective PR comment chains (In this case #28 ) as they are not part of the main code.
