### ISSUE TITLE
Cheap Weekend Trip Opportunity

### ISSUE THREAD

**Issue by jtj0009** [prueker/METARMap#38]
As a user who is a pilot, I would like the metar map to graphically let me know of a cheap weekend trip opportunity in which I would get a tailwinds in both directions.  The software would take input of users home airport and several airports of interest.  The software would check winds aloft forecast each Wednesday/Thursday for Friday and Sunday and, if forecast results in tailwinds on Friday AND tailwinds on Sunday, let user know of any available cheap weekend trip opportunity.

**Comment by prueker** [comment]
It's a little beyond the intentionally reasonably simple scope of my metarmap project, so it is easy to follow for others to build.
