### ISSUE TITLE
Modify for Raspberry Pi Pico?

### ISSUE THREAD

**Issue by derekantrican** [prueker/METARMap#39]
Is there a chance this project could be modified to work for the Raspberry Pi Pico? I don't really see why not (unless there's some missing feature of micro python that I'm not aware of). Mostly seems like a few concepts based on a "regular" raspberry pi & a linux system would have to be changed.

**Comment by prueker** [comment]
Yes, it might work assuming that the micro python libraries can support the neopixel libraries and that memory for loading the live weather data doesn't run into issues.

I'm a little busy at the moment, so I don't have enough time to tinker around to try it, but if someone wants to go try, feel free to.

**Comment by tiuchs** [comment]
@derekantrican did you succeed in porting the project to a Raspberry Pi Pico?

**Comment by derekantrican** [comment]
No, I haven't put any effort into this. I was just asking out of theory
