### ISSUE TITLE
refresh not running

### ISSUE THREAD

**Issue by awdr210** [prueker/METARMap#40]
Philip, great project here, and the instructions are relatively simple, even for a noob like me. I'm having one issue with the refresh. I've kept the interval at five minutes, but it runs metar.py for 300 seconds and does not refresh. On boot, refresh.sh runs from crontab and I get the metarpid.pid, however, it does not overwrite when I manually push using ./refresh.sh. Instead, I get 'metarpid.pid'$'\r'. In turn, both lightsoff.sh and refresh.sh have an error "pkill: pidfile not valid"

Any ideas or recommendations on fix?

**Comment by prueker** [comment]
Sounds like an encoding problem between windows and linux around carriage returns (the \r printed hints at that).
Try recreating the file from another notepad editor.
