### ISSUE TITLE
Changes to the API dataserver effective today

### ISSUE THREAD

**Issue by cbronner35** [prueker/METARMap#47]
Look like they finally did the changeover on aviationweather.gov and the dataserver has changed addresses. Which means the maps won't work. I was messing with it and trying to adapt the new dataserver to the code but we're medivac so of course I get a call right in the middle of it. If someone has already adapted the code please message me the new dataserver url string and save me a couple hours trying to figure it out lol

**Comment by echo-alfa** [comment]
Looks like the new location is:

https://aviationweather.gov/cgi-bin/data/dataserver.php?requestType=retrieve&hoursBeforeNow=4&format=xml&mostRecent=true&dataSource=metars&stationString=EGSS

**Comment by cbronner35** [comment]
Yeah I've generated using the API tool but don't know how to adapt it to the metar.py. It looks like you just used that tool as well using a single station identifier. This won't help to convert the old dataserver to the new one and make the code work with it. Unless I'm missing something

**Comment by echo-alfa** [comment]
The URL I’ve posted above is a direct replacement for the old url. Not had a chance to test it yet but you should be able to drop that into the metar.py line 146.

**Comment by cbronner35** [comment]
It can't be a direct replacement especially if referencing EGSS on your stationstring. Unless your map only has one point which is London

**Comment by echo-alfa** [comment]
OLD
url = "https://www.aviationweather.gov/adds/dataserver_current/httpparam?dataSource=metars&requestType=retrieve&format=xml&hoursBeforeNow=5&mostRecentForEachStation=true&stationString=" + ",".join([item for item in airports if item != "NULL"])

NEW
url = "https://aviationweather.gov/cgi-bin/data/dataserver.php?requestType=retrieve&hoursBeforeNow=5&format=xml&mostRecent=true&dataSource=metars&stationString=" + ",".join([item for item in airports if item != "NULL"])

**Comment by cbronner35** [comment]
Sweet thanks! I have something similar but we got another call so I'll try
your when I get back to base and let you know!

**Comment by mschultz21** [comment]
Thanks for finding this new URL! I was wondering why my map wouldn't work today.

Something I noticed with the new URL though, even if I put in a list of airports after stationString, it's only returning 1 airport at a time. Did you also encounter this error?

**Comment by echo-alfa** [comment]
A few adjustments required.

`url = "https://aviationweather.gov/cgi-bin/data/dataserver.php?dataSource=metars&requestType=retrieve&format=xml&hoursBeforeNow=5&mostRecentForEachStation=true&stationString=" + ",".join([item for item in airports if item != "NULL"])`

I missed out the "ForEachStation" so it was only returning one result. The above solves that. 

Visibility seems to be returned as "6+" now and the + throws up and error. Fixed this with the below:

`if metar.find('visibility_statute_mi') is not None:
            visibility = metar.find('visibility_statute_mi').text
            if '+' in visibility:
                visibility = visibility.replace('+', '')  # Removing '+' character
            vis = int(round(float(visibility)))`

**Comment by mschultz21** [comment]
Using your logic to replace the '+' with '' is giving me a syntax error for some reason, specifically pointing to this part `visibility: visibility = visibility.replace('+', '')`

I'm not well versed in Python, specifically shorthand notations so I'm not sure what's going on here

**Comment by echo-alfa** [comment]
<img width="458" alt="Screenshot 2023-10-16 233221" src="https://github.com/prueker/METARMap/assets/96354017/af5c0a17-bf68-498f-ad5c-83898d61c3bd">

Make sure you have your indentation is correct.

**Comment by mschultz21** [comment]
Yep that would be my problem! Thank you for pointing out my stupidity.

**Comment by echo-alfa** [comment]
Hey, not at all. Easily done!

**Comment by cbronner35** [comment]
Nice echo-alfa! Worked like a charm! Appreciate you diving into this my crew and I appreciate it!

**Comment by prueker** [comment]
Thanks for the quick discussion for the fix, I'll try to update the script by the weekend when I get a moment based on your suggested fix here.

**Comment by prueker** [comment]
The issue was fixed with #48 thanks to @moisedo
