### ISSUE TITLE
Is the .GOV site down?

### ISSUE THREAD

**Issue by speedtoys** [prueker/METARMap#49]
https://www.aviationweather.gov/adds/dataserver_current/httpparam?dataSource=metars&requestType=retrieve&format=xml&hoursBeforeNow=5&mostRecentForEachStation=true&stationString=KRHV

---
Not Found
The requested URL was not found on this server.

**Comment by prueker** [comment]
The aviationweather.gov service changed - you can refer to #47 for the discussion and the latest version of [metar.py](https://github.com/prueker/METARMap/blob/main/metar.py) has already been fixed with change #48.
