### ISSUE TITLE
Airport count - index error

### ISSUE THREAD

**Issue by nesincg** [prueker/METARMap#50]
I seem to run into this with 0 being a number or I miscount LEDs. Is there anyway to count the airports in the file first? i++ or something. I know I'm so green at this stuff. Just an idea. 

Thanks for making the FAA change and winds fix so quickly.

**Comment by prueker** [comment]
Good idea, I just updated the script to print out a warning if this happens and print the airport count vs initialized LED_COUNT.

As a side note - you can always set the LED_COUNT to be higher than the amount of airports you have, it's only a problem if it's lower.
