### ISSUE TITLE
aviation weather gov new API

### ISSUE THREAD

**Issue by yaofuzhou** [prueker/METARMap#51]
Hello - aviationweather.gov had an overhaul, including its API. I have fixed my METAR map for the overhaul. Let me know if you want it and I can send you a pull request! :) Thanks!

**Comment by echo-alfa** [comment]
A fix for this was published earlier today. 👍🏻

**Comment by prueker** [comment]
Already fixed as mentioned, refer to #47 for the discussion and the fix.
The latest version of metar.py is updated with the fix.
