### ISSUE TITLE
Update aviationweather api endpoint

### ISSUE THREAD

**Issue by lostlocalhost** [prueker/METARMap#52]
aviation weather changed their api format.

Update to this in ym own proj:
url = "https://aviationweather.gov/cgi-bin/data/dataserver.php?requestType=retrieve&dataSource=metars&format=xml&hoursBeforeNow=5&mostRecentForEachStation=true&stationString=" + ",".join([item for item in list(airport_dict.keys()) if "NULL" not in item])

Also, the line pulling visibility will have to change to just pull the value and not float it due to return being "10+" for most vfr results.

here's the new docs for context:
https://aviationweather.gov/data/api/#/Dataserver/dataserverMetars

**Comment by prueker** [comment]
Already fixed. Refer to #47

**Comment by lostlocalhost** [comment]
Looking for facepalm emoji...
nj
