### ISSUE TITLE
 Handling NoneType Error in stationId and Missing <flight_category> Element

### ISSUE THREAD

**Issue by moisedo** [prueker/METARMap#61]
**1. Handling NoneType Error in stationId Concatenation:**
The script crashed due to attempting to concatenate a **`None`** value with a string. This was addressed by checking if **`stationId`** obtained from the XML was **`None`** and handling it appropriately before usage.

**2. Handling Missing <flight_category> Element:**
Some METAR data entries lacked the **`<flight_category>`** element, which led to errors when the script tried to access its text. Introduced a check for the presence of this element and provided a default value when missing.

**Proposed solution:**
1. Check for None in stationId:
Before using **`stationId`** in operations that assume it is a string, verify it isn't **`None`**. If it is, skip processing the current METAR data.
```python
for metar in root.iter('METAR'):
    stationId = metar.find('station_id').text if metar.find('station_id') is not None else None
    if stationId is None:
        print("Missing or malformed station ID, skipping METAR element:")
        print(ET.tostring(metar, encoding='unicode'))
        continue
```

- Handling **`None`** for **`stationId`** ensures the script does not crash when data is missing, improving its robustness.

2. Default Value for Missing <flight_category>:
Check if the **`<flight_category>`** element exists and provide a default value if it doesn't. This prevents attempts to access attributes of a **`None`** object.

```python
flight_category_element = metar.find('flight_category')
if flight_category_element is None or flight_category_element.text is None:
    flightCategory = "Unknown"
    print(f"Flight category missing for {stationId}, using default: {flightCategory}")
else:
    flightCategory = flight_category_element.text
```

- Providing defaults for missing **`<flight_category>`** ensures the script can handle incomplete METAR data gracefully without breaking.

Submitting PR for this fix.

**Comment by prueker** [comment]
Added fix for missing station id now here: 4bb71d6abb040e67218201189ea46d7e23899fed
