### ISSUE TITLE
Pixelsoff in documentation

### ISSUE THREAD

**Issue by o62** [prueker/METARMap#7]
This isn't really an issue in the code but for the documentation, nothing mentions needing to adjust the pixelsoff.py script to match the lights you have. I had 61 LEDs so the 50 scripted in the original document needed change. It was easy enough for me to find and fix, maybe not so much for new folks.

**Comment by prueker** [comment]
Good call, I've added note to the readme to also update the pixelsoff.py script for the LED_COUNT.
